### ISSUE TITLE
Implement different levels of entities

### ISSUE THREAD

**Issue by sebastian-raubach** [germinateplatform/germinate#14]
This will include "accessions", "plant/plot" and "sample". Each item in `germinatebase` can be linked to it's "parent entity" (different from pedigree).
This will allow us to associate phenotypic, compound, genotypic and allele frequency data with different levels of entities.

Various queries and parts of the interface will have to be modified to accommodate this change.

**Comment by quacksawbones** [comment]
Apologies for the static. I have not had a clear run at this until recently.

I've made some modifications to the germinate database to include:

- An additional table `entitytype` (which consists of `id` <INT 11, PK>, `name` <VARCHAR 255, AK>, `description` <VARCHAR 255, AK(?)>, `created_on` <DATETIME>, `updated_on` <TIMESTAMP> ) 

- adding two columns to `germinatebase`:
-- `entityparent_id` <INT11, FK to `germinatebase.id`>
-- `entitytype_id` <INT 11, FK to `entitytype.id`>

The changes above will allow a generic hierarchy system to be implemented at the project's discretion.

Should I get these changes to you via a git push with the database changes to the SQL file in this project?

![germinate db extension v2 1](https://user-images.githubusercontent.com/1300104/36293347-cdde4e7c-132c-11e8-8464-124efa346a17.jpg)

**Comment by sebastian-raubach** [comment]
We're currently working on a branch of this repo called "samples":

**Comment by quacksawbones** [comment]
That's awesome, mate. Thanks for the update.

It might not be a bad idea to include our hierarchy (i.e. Accession -> Plant/Plot -> Sample) as an example rather than imported as records into the database (though that might already be on the cards). Our sample structure has got more complex since we last spoke, but will still be fine for implementation in terms of the `entityparent_id` and `entitytype_id` structure.

I'm thinking of broad implementation across various projects rather than specific for our project purposes.

**Comment by quacksawbones** [comment]
Regarding the different entity types in Germinate, I've noticed that no `germinatebase` records are displayed if you have no `entitytype` selected in the filter.

Is there any way that Germinate can display everything (i.e. all entity types) when there is no filter, and then only display specific entity types when they are added to the filter?

Should the default entitytype be Accession or everything?

**Comment by sebastian-raubach** [comment]
I can't reproduce this. When I clear the filter, I see all items.
Make sure every item in `germinatebase` has an `entitytype_id`.
Also, please be aware that you're using a branch of Germinate that is actively being developed. Things may and will change until the release of version 3.5.0, so please don't rely on anything that you currently see in this branch.
