### ISSUE TITLE
Rename "class" column in "compounds" to "compound_type" or similar

### ISSUE THREAD

**Issue by quacksawbones** [germinateplatform/germinate#17]
I have found an interesting quirk in the database. When using Python for my data import, I can't add any data to the `class` column in the `compounds` table, as Python interprets `class` as a built in function/variable and I cannot override it without breaking many other things. I suspect this will be the same with many other languages.

Can the `class` column in `compounds` please be renamed to something else, such as `compound_type` or `compound_class`? This will also mean the associated java file `Compound.java`, `CompoundTable.java` and `CompoundService.java` will need to make a similar change to continue functionality.

**Comment by sebastian-raubach** [comment]
I don't know python well, but is there no way to put class in some kind of quotes `, ' or "?
We may consider renaming the column for the next release.
