### ISSUE TITLE
v3.5.0 does not show relationship between accessions

### ISSUE THREAD

**Issue by quacksawbones** [germinateplatform/germinate#23]
Hi Folks,

The plant/plot and sample entity relationships work great, but unfortunately, I'm having difficulty linking accessions (we have two populations that have a number of identical members, so we'd like to link them) and have the relationship displayed under "Entity". Relationships between plant and samples, plants and plants, and samples and samples do not have this bug.

Working example of the germinatebase table that shows the bug attached.

[MWE_germinatebase_no_accession_parents.txt](https://github.com/germinateplatform/germinate/files/2125931/MWE_germinatebase_no_accession_parents.txt)

**Comment by sebastian-raubach** [comment]
If I understand you correctly, you're trying to say that B has A as it's entity parent and they're both accession entities, is that right?
Could you explain a use case for having an accession -> accession relationship that isn't covered by the pedigree system of Germinate?

**Comment by quacksawbones** [comment]
Apologies, Pedigree will work just fine.

Happy to have this closed under "Problem was user not aware of applicable function"

**Comment by sebastian-raubach** [comment]
No worries!
