### ISSUE TITLE
Got error while generating file from hdf5 

### ISSUE THREAD

**Issue by lenora09** [germinateplatform/germinate#27]

**Comment by sebastian-raubach** [comment]
How long did it take to get to this point? Did your session maybe time out? Also check the property: `Germinate.KeepTemporaryFileForHours`

**Comment by sebastian-raubach** [comment]
There isn't a lot of information to work with. Did you try increasing the config properties? Also, what data sizes are you dealing with?
Are you sure there isn't another log file under <Tomcat>/logs ?
